---

- name: Enable fractional scaling
  ansible.builtin.command: |
    gsettings set org.gnome.mutter experimental-features "[ 'scale-monitor-framebuffer' ]" 
  tags: gnome

- name: Enable dark mode
  ansible.builtin.command: |
    gsettings set org.gnome.desktop.interface color-scheme prefer-dark
  tags: gnome

- name: Enable tap-to-click
  ansible.builtin.command: |
    gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true
  tags: gnome

