---

- name: install rpm-fusion repositories
  dnf:
    state: present
    disable_gpg_check: yes
    name:
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_facts.distribution_version }}.noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_facts.distribution_version }}.noarch.rpm
  become: yes
  tags: rpmfusion

- name: install ffmpeg codecs
  dnf:
    name:
      - ffmpeg
    state: latest
    allowerasing: true 
  become: yes
  tags: rpmfusion

- name: update multimedia group
  dnf:
    name:
      - "@multimedia"
    state: latest
    install_weak_deps: false 
    exclude: PackageKit-gstreamer-plugin
  become: yes
  tags: rpmfusion

- name: update sound-and-video group
  dnf:
    name:
      - "@sound-and-video"
    state: latest
  become: yes
  tags: rpmfusion

- name: install hardware codecs
  dnf:
    name:
      - intel-media-driver
      - libva-intel-driver
      - mesa-va-drivers
      - mesa-vdpau-drivers
      - mesa-va-drivers.i686
      - mesa-vdpau-drivers.i686
      - nvidia-vaapi-driver
      - rpmfusion-free-release-tainted
      - rpmfusion-nonfree-release-tainted
    state: latest
    allowerasing: true 
  become: yes
  tags: rpmfusion

- name: install libdvdcss
  dnf:
    name: libdvdcss
    state: latest
  become: yes
  tags: rpmfusion

- name: install tainted firmware
  dnf:
    name: "*-firmware"
    state: latest
    enablerepo: rpmfusion-nonfree-tainted
  become: yes
  tags: rpmfusion

