---

- name: add 1Password YUM repository key
  ansible.builtin.rpm_key:
    key: https://downloads.1password.com/linux/keys/1password.asc
    state: present
  become: yes
  tags: 1password

- name: add 1Password YUM repository
  ansible.builtin.yum_repository:
    name: 1password
    description: 1Password Stable Channel
    baseurl: https://downloads.1password.com/linux/rpm/stable/\$basearch
    gpgcheck: true
    gpgkey: https://downloads.1password.com/linux/keys/1password.asc
  become: yes
  tags: 1password

- name: install 1Password and 1Password CLI
  dnf:
    name:
      - 1password
      - 1password-cli
    state: present
  become: yes
  tags: 1password

- name: ensure /etc/1password directory exists
  file:
    path: /etc/1password
    state: directory
  become: yes
  tags: 1password

- name: add 1Password custom browsers exemptions
  copy:
    content: |
      firefox
      vivaldi
      vivaldi-bin
      vivaldi-stable
    dest: /etc/1password/custom_allowed_browsers
    owner: 'root'
    group: 'root'
    mode: '0755'
  become: yes
  tags: 1password

