---

- name: update host packages
  dnf:
    name: "*"
    state: latest
  become: yes
  tags: base-system

- name: enable flatpak repositories
  include_tasks: flatpak.yml
  tags: base-system, flatpak

- name: manage applications
  include_tasks: applications.yml
  tags: base-system, applications

- name: install 1Password
  include_tasks: 1password.yml
  tags: base-system, applications, 1password

- name: install prompt / ptyxis
  include_tasks: prompt-ptyxis.yml
  tags: base-system, applications, terminal

- name: tweak gnome settings
  include_tasks: gnome-settings.yml
  tags: base-system, gnome

- name: remove unnecessary packages
  dnf:
    autoremove: yes
  become: yes
  tags: base-system

